### ISSUE TITLE
.scn exists but failed to load

### ISSUE THREAD

**Issue by VIGAR0108** [Stanford-ILIAD/explore-eqa#1]
Hi!
I am currently encountering an issue while running the `test_scene.py` and hope you might help me troubleshoot it.  Here is the error message I receive:

> [Error]:[Scene] SemanticScene.cpp(137)::loadSemanticSceneDescriptor : SSD Load Failure! File with SemanticAttributes-provided name '/data/dataset/hm3d/hm3dsem-train/00424-Hsk3jDzNySy/Hsk3jDzNySy.basis.scn` exists but failed to load.

Looking forward to your guidance,
Thanks!

**Comment by allenzren** [comment]
Hi there! I have seen such error before, but it does not affect using the simulator (you can try saving the observation [here](https://github.com/Stanford-ILIAD/explore-eqa/blob/c3acdf80bbd4d527a5a4eba5898687704a92e27c/test_scene.py#L117) and see if it looks alright). Was there any other error that you ran into?

**Comment by VIGAR0108** [comment]
I just saved an observation and it seems all good, Thanks!
