### ISSUE TITLE
Inquiry about prism-dinosiglip+7b has no attribute get_loss

### ISSUE THREAD

**Issue by William-Wu-Tao** [Stanford-ILIAD/explore-eqa#5]

**Comment by TrishnaC** [comment]
I am experiencing the same issue. Could you please share how to solve it?

**Comment by xwjim** [comment]
I am experiencing the same issue. Could you please share how to solve it?

**Comment by William-Wu-Tao** [comment]
The error "prism-dinosiglip+7b has no attribute get_loss" indicates that the `get_loss` method is missing from one of the files in your locally cloned repository. This can happen if the repository was not fully updated or if some files were accidentally modified.To resolve this issue:

1. Go to the original GitHub repository for `prism-dinosiglip+7b`.
2. Navigate to the file that should contain the `get_loss` method (likely a model definition file like `model.py` or `loss.py`).
3. Copy the entire content of that file from GitHub.
4. Replace the corresponding file in your local repository with the copied content.

**Comment by UchihaBarry** [comment]
> The error "prism-dinosiglip+7b has no attribute get_loss" indicates that the `get_loss` method is missing from one of the files in your locally cloned repository. This can happen if the repository was not fully updated or if some files were accidentally modified.To resolve this issue:
> 
> 1. Go to the original GitHub repository for `prism-dinosiglip+7b`.
> 2. Navigate to the file that should contain the `get_loss` method (likely a model definition file like `model.py` or `loss.py`).
> 3. Copy the entire content of that file from GitHub.
> 4. Replace the corresponding file in your local repository with the copied content.

thank u for ur reply. However, when I search the get_loss function in https://github.com/TRI-ML/prismatic-vlms, there is no file contain this function.
